data_dir: /home/kuto/kaggle/kaggle-sleep-v2/data/child-mind-institute-detect-sleep-states
output_dir: /home/kuto/kaggle/kaggle-sleep-v2/output
processed_dir: /home/kuto/kaggle/kaggle-sleep-v2/output/processed_data
model_dir: /home/kuto/kaggle/kaggle-sleep-v2/output/train
sub_dir: ./