data_dir: /home/kuto/kaggle/kaggle-child-mind-institute-detect-sleep-states/data/child-mind-institute-detect-sleep-states
processed_dir: /home/kuto/kaggle/kaggle-child-mind-institute-detect-sleep-states/processed_data
output_dir: /home/kuto/kaggle/kaggle-child-mind-institute-detect-sleep-states/output
model_dir: /home/kuto/kaggle/kaggle-child-mind-institute-detect-sleep-states/output/train
sub_dir: ./