# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: inference
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/${weight.run_name}
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - dir: local
  - model: Spec2DCNN
  - feature_extractor: CNNSpectrogram
  - decoder: UNet1DDecoder
  - _self_

exp_name: dummy
phase: test
weight:
  exp_name: ${exp_name}
  run_name: single
  model_name: "best_model.pth"  # or "latest_model.pth"

model:
  encoder_weights: null

seed: 42
duration: 5760 # durationは32の倍数
downsample_rate: 2 # durationをdownsample_rateで割った値がnum_framesになる
upsample_rate: 1
batch_size: 64
num_workers: 2
use_amp: true

# loss
inbalanced_loss_weight: 1

# dataset
slide_tta: false
make_submission: true

# augmentation
augmentation:
  mixup_prob: 0.0
  mixup_alpha: 0.4
  cutmix_prob: 0.0
  cutmix_alpha: 0.4

# post_process
post_process:
  score_th: 0.02
  distance: 10
  low_pass_filter_hour: 1
  window_size: 100
  event_weight: 1.0
# label
labels:
  - "awake"
  - "event_onset"
  - "event_wakeup"

# feature
features:
  - "anglez"
  - "enmo"
  - "hour_sin"
  - "hour_cos"
