# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: train
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: local
  - model: Spec2DCNN
  - feature_extractor: CNNSpectrogram
  - decoder: UNet1DDecoder
  - split: fold_0

seed: 42
exp_name: dummy
notes: ""
duration: 5760 # duration * 5 = 秒数
downsample_rate: 2
upsample_rate: 1
relabeling: false
# training
epoch: 50
batch_size: 32
num_workers: 24
accelerator: auto
use_amp: true
debug: false
gradient_clip_val: 1.0
accumulate_grad_batches: 1
monitor: val_score
monitor_mode: max
check_val_every_n_epoch: 1

# loss
imbalanced_loss_weight: 1

# Dataset
offset: 10
sigma: 10  # for gaussian label
scale: 10  # for laplace label
bg_sampling_rate: 0.5
slide_tta: false
label_type: gaussian  # or laplace
use_noisy_event_label: false

# augmentation
augmentation:
  mixup_prob: 0.0
  mixup_alpha: 0.4
  cutmix_prob: 0.0
  cutmix_alpha: 0.4
  local_shuffle_prob: 0.0
  local_shuffle_window_size: 3
  swap_mixup_prob: 0.0
  swap_mixup_alpha: 0.4
  swap_event_prob: 0.5
  swap_event_window_size: 100  # 5s*2*100 = 1000s = 16.6min
  swap_channels: [0, 1]  # swapする特徴量の次元
  
# post_process
post_process:
  score_th: 0.001
  distance: 70
  low_pass_filter_hour: 5
  window_size: 100
  event_weight: 1.0

# label
labels:
  - "awake"
  - "event_onset"
  - "event_wakeup"

# feature
features:
  - "anglez"
  - "enmo"
  - "hour_sin"
  - "hour_cos"

# optimizer
optimizer:
  lr: 0.0005

# scheduler
scheduler:
  warmup_step_rate: 0
